
title: "Honest Academia"
description: "A project for postdocs: reviews of unethical academic supervisors and research labs."
baseurl: "/WillBeRenamedLater_HA"
url: "https://cherepan.github.io"

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

kramdown:
  input: GFM