yaml


title: "Academic Blacklist"
description: "A project for postdocs: reviews of unethical academic supervisors and research labs."
baseurl: "/WillBeRenamedLater_HA"
url: "https://cherepan.github.io"

theme: minima
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

kramdown:
  input: GFM


